services:
  - type: static_site
    name: react-frontend-app # Bạn có thể đổi tên này tùy ý
    env: static
    rootDir: frontend # Báo cho Render biết code FE nằm ở thư mục này
    buildCommand: npm install && npm run build # Lệnh cài đặt và đóng gói code
    staticPublishPath: dist # Thư mục Vite tạo ra sau khi build
    
    # Cấu hình này cực kỳ quan trọng cho React để không bị lỗi 404 khi F5 trang
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
